baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Dolkons Hugo Site'
theme: "PaperMod"

socialIcons:
  - name: twitter
    url: "https://twitter.com/"
  - name: stackoverflow
    url: "https://stackoverflow.com"
  - name: github
    url: "https://github.com/"
  - name: telegram
    url: "telegram.org"
    
params:
  showShareButtons: true
  shareButtons: ["telegram", "linkedin", "twitter"]
  description: "Test description"
  author: "Dolkons"

