main:
  - url: /
    name: "🏠"
    weight: 1

  - url: /about/
    name: О проекте
    weight: 2

  - url: /qa/
    name: QA
    weight: 3

  - url: /yoga/
    name: Йога
    weight: 4

  - url: /books/
    name: Книги
    weight: 5