main:
  - weight: 1
    identifier: home
    name: home
    url: /
  - weight: 1
    identifier: qa
    pre: ''
    post: ''
    name: QA
    url: /qa/
    title: 'Всё о тестировании'
  - weight: 2
    identifier: yoga
    pre: ''
    post: ''
    name: Yoga
    url: /yoga/
    title: 'Всё о йоге'