defaultTheme: auto
gitRepo: ''
fingerprint: ''
dateFormat: '02-09-2022'
title: My cool site
description: This is my cool site123
images:
  - /logo.png
header:
  desktopMode: fixed
  mobileMode: auto
  title:
    logo: ''
    name: ''
    pre: ''
    post: ''
    typeit: false
footer:
  enable: true
  custom: ''
  hugo: true
  copyright: true
  author: true
  since: 2019
  icp: ''
  license: >-
    <a rel="license external nofollow noopener noreffer"
    href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
    BY-NC 4.0</a>
section:
  paginate: 20
  dateFormat: 01-02
  rss: 10
list:
  paginate: 20
  dateFormat: 01-02
  rss: 10
app:
  title: My cool site
  noFavicon: false
  svgFavicon: ''
  themeColor: '#ffffff'
  iconColor: '#5bbad5'
  tileColor: '#da532c'
search:
  enable: true
  type: lunr
  contentLength: 4000
  placeholder: ''
  maxResultLength: 10
  snippetLength: 30
  highlightTag: em
  absoluteURL: false
  algolia:
    index: ''
    appID: ''
    searchKey: ''
home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ''
    avatarURL: /images/avatar.png
    title: ''
    subtitle: This is My New Hugo Site
    typeit: true
    social: true
    disclaimer: ''
  posts:
    enable: true
    paginate: 6
    defaultHiddenFromHomePage: false
social:
  GitHub: xxxx
  Linkedin: ''
  Twitter: xxxx
  Instagram: xxxx
  Facebook: xxxx
  Telegram: xxxx
  Medium: ''
  Gitlab: ''
  Youtubelegacy: ''
  Youtubecustom: ''
  Youtubechannel: ''
  Tumblr: ''
  Quora: ''
  Keybase: ''
  Pinterest: ''
  Reddit: ''
  Codepen: ''
  FreeCodeCamp: ''
  Bitbucket: ''
  Stackoverflow: ''
  Weibo: ''
  Odnoklassniki: ''
  VK: ''
  Flickr: ''
  Xing: ''
  Snapchat: ''
  Soundcloud: ''
  Spotify: ''
  Bandcamp: ''
  Paypal: ''
  Fivehundredpx: ''
  Mix: ''
  Goodreads: ''
  Lastfm: ''
  Foursquare: ''
  Hackernews: ''
  Kickstarter: ''
  Patreon: ''
  Steam: ''
  Twitch: ''
  Strava: ''
  Skype: ''
  Whatsapp: ''
  Zhihu: ''
  Douban: ''
  Angellist: ''
  Slidershare: ''
  Jsfiddle: ''
  Deviantart: ''
  Behance: ''
  Dribbble: ''
  Wordpress: ''
  Vine: ''
  Googlescholar: ''
  Researchgate: ''
  Mastodon: ''
  Thingiverse: ''
  Devto: ''
  Gitea: ''
  XMPP: ''
  Matrix: ''
  Bilibili: ''
  Discord: ''
  DiscordInvite: ''
  Lichess: ''
  ORCID: ''
  Pleroma: ''
  Kaggle: ''
  MediaWiki: ''
  Plume: ''
  HackTheBox: ''
  RootMe: ''
  Phone: ''
  Email: xxxx@xxxx.com
  RSS: true
page:
  hiddenFromHomePage: false
  hiddenFromSearch: false
  twemoji: false
  lightgallery: false
  ruby: true
  fraction: true
  fontawesome: true
  linkToMarkdown: true
  rssFullText: false
  toc:
    enable: true
    keepStatic: true
    auto: true
  math:
    enable: true
    inlineLeftDelimiter: ''
    inlineRightDelimiter: ''
    blockLeftDelimiter: ''
    blockRightDelimiter: ''
    copyTex: true
    mhchem: true
  code:
    copy: true
    maxShownLines: 50
  mapbox:
    accessToken: ''
    lightStyle: 'mapbox://styles/mapbox/light-v10?optimize=true'
    darkStyle: 'mapbox://styles/mapbox/dark-v10?optimize=true'
    navigation: true
    geolocate: true
    scale: true
    fullscreen: true
  share:
    enable: true
    Twitter: true
    Facebook: true
    Linkedin: false
    Whatsapp: false
    Pinterest: false
    Tumblr: false
    HackerNews: true
    Reddit: false
    VK: false
    Buffer: false
    Xing: false
    Line: true
    Instapaper: false
    Pocket: false
    Flipboard: false
    Weibo: true
    Blogger: false
    Baidu: false
    Odnoklassniki: false
    Evernote: false
    Skype: false
    Trello: false
    Mix: false
  comment:
    enable: false
    disqus:
      enable: false
      shortname: ''
    gitalk:
      enable: false
      owner: ''
      repo: ''
      clientId: ''
      clientSecret: ''
    valine:
      enable: false
      appId: ''
      appKey: ''
      placeholder: ''
      avatar: mp
      meta: ''
      pageSize: 10
      lang: ''
      visitor: true
      recordIP: true
      highlight: true
      enableQQ: false
      serverURLs: ''
      emoji: ''
    facebook:
      enable: false
      width: 100%
      numPosts: 10
      appId: ''
      languageCode: ''
    telegram:
      enable: false
      siteID: ''
      limit: 5
      height: ''
      color: ''
      colorful: true
      dislikes: false
      outlined: false
    commento:
      enable: false
    utterances:
      enable: false
      repo: ''
      issueTerm: pathname
      label: ''
      lightTheme: github-light
      darkTheme: github-dark
    giscus:
      enable: false
      repo: ''
      repoId: ''
      category: Announcements
      categoryId: ''
      lang: ''
      mapping: pathname
      reactionsEnabled: '1'
      emitMetadata: '0'
      inputPosition: bottom
      lazyLoading: false
      lightTheme: light
      darkTheme: dark
  library:
    css: {}
    js: {}
  seo:
    images: []
    publisher:
      name: ''
      logoUrl: ''
typeit:
  speed: 100
  cursorSpeed: 1000
  cursorChar: '|'
  duration: -1
verification:
  google: ''
  bing: ''
  yandex: ''
  pinterest: ''
  baidu: ''
seo:
  image: ''
  thumbnailUrl: ''
analytics:
  enable: false
