author: "Константин Долгий"
info: "Full Stack QA Engineer"
description: "Мой персональный веб-сайт"
colorScheme: "dark"
avatarurl: "/images/avatar.jpg"

social:
  - name: telegram
    icon: fa fa-telegram fa-2x
    weight: 1
    url: 'https://t.me/dolkons'
  - name: Github
    icon: fa fa-github fa-2x
    weight: 2
    url: 'https://github.com/dolkons/'