main:
  - weight: 1
    identifier: home
    name: 🏠
    url: /
  - weight: 2
    identifier: qa
    name: QA
    url: /qa/
    title: 'Всё о тестировании'
  - weight: 3
    identifier: yoga
    name: Yoga
    url: /yoga/
    title: 'Всё о йоге'