name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clean install dependencies
        run: npm ci

      - name: Check types
        run: npm run typecheck

      - name: Lint source
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Build project
        run: npm run build

      - name: Deploy to Yandex Object Storage
        uses: nekitcorp/yandex-storage-website-action@v2
        with:
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          working-directory: ./build
          clear: true
